version: "3.7"
services:
  schemaspy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output/${DB}:/output
    networks:
      - ${DB}_default
    environment:
      - DB_NAME=${DB_NAME:-groot}
      - DB_HOST=${DB_HOST:-groot-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-}

networks:
  groot_default:
    external: true
  gateway_default:
    external: true
  rocket_default:
    external: true
  heimdall_default:
    external: true
