
version: "2"
services:
  schemaspy:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB=${DB}
    volumes:
      - ./output/${DB}:/output
    networks:
      - ${DB}_default

networks: 
  groot_default:
    external: true
  gateway_default:
    external: true
  rocket_default:
    external: true
  heimdall_default:
    external: true
      