
version: "2"
services:
  schemaspy:
    container_name: schemaspy
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: output
      target: /output
      