
steps:
  - label: ":docker: Audit dependencies"
    skip: true
    command: bash .buildkite/scripts/audit_dependencies.sh
    soft_fail: true
    agents:
      queue: 'annalise-build'

  - wait

  - label: ':docker: Build Docker Image & Publish'
    command: bash scripts/build_and_publish.sh
    agents:
      queue: 'annalise-build'

  - wait

  - label: ':docker: Test/Audit/Monitor Docker Image for Vulnerabilities using Synk'
    command: bash scripts/snyk_container_test.sh
    agents:
      queue: 'annalise-build'
