name: Build Docker images

on:
  release:
    types: [published]

# for debugging
#on:
#  push

env:
  PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Extract Branch/Tag Names
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      -
        name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
        with:
          platforms: arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      -
        name: Docker Buildx Bake
        uses: docker/bake-action@v2.2.0
        with:
          push: true
          set: |
            *.cache-to=type=gha,mode=max,compression=zstd
            *.cache-from=type=gha,mode=max,compression=zstd