name: Build Docker images(SchemaSpy Snapshot version)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.1.0

      -
        name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
        with:
          platforms: arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.3.0
      -
        name: Docker Buildx Bake(Temurin-snapshot)
        uses: docker/bake-action@v2.3.0
        with:
          files: docker-bake-snapshot.hcl
          push: true
          set: |
            *.cache-to=type=gha,mode=max
            *.cache-from=type=gha