name: Build Docker images

on:
  release:
    types: [published]

# for debugging
#on:
#  push

env:
  PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Extract Branch/Tag Names
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      -
        name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
        with:
          platforms: arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      -
        name: Docker Buildx Bake(Temurin)
        uses: docker/bake-action@v2.3.0
        with:
          files: docker-bake-temurin.hcl
          push: true
          set: |
            *.cache-to=type=gha,mode=max
            *.cache-from=type=gha
      -
        name: Docker Buildx Bake(OpenJDK)
        uses: docker/bake-action@v2.3.0
        with:
          files: docker-bake.hcl
          push: true
          set: |
            *.cache-to=type=gha,mode=max
            *.cache-from=type=gha